export const START = 'START'
export const MOVE_LEFT = 'MOVE_LEFT'
export const MOVE_RIGHT = 'MOVE_RIGHT'
export const MOVE_DOWN = 'MOVE_DOWN'
export const MOVE_END = 'MOVE_END'
export const ROTATE = 'ROTATE'